-- ============================================================
-- Seed: Problems data (from the frontend mock data + extras)
-- Run this AFTER both migrations in Supabase SQL Editor
-- ============================================================

insert into public.problems
  (title, difficulty, topic, tags, acceptance, xp_reward, description, examples, constraints, starter_code, leetcode_url, neetcode_url)
values
(
  'Two Sum', 'Easy', 'Arrays', ARRAY['Google','Amazon','Meta'],
  92.0, 50,
  'Given an array of integers `nums` and an integer `target`, return *indices of the two numbers such that they add up to target*. You may assume that each input would have **exactly one solution**, and you may not use the same element twice.',
  '[{"input":"nums = [2,7,11,15], target = 9","output":"[0,1]","explanation":"Because nums[0] + nums[1] == 9, we return [0, 1]."},{"input":"nums = [3,2,4], target = 6","output":"[1,2]","explanation":"nums[1] + nums[2] == 6."},{"input":"nums = [3,3], target = 6","output":"[0,1]","explanation":"nums[0] + nums[1] == 6."}]'::jsonb,
  ARRAY['2 <= nums.length <= 10^4','-10^9 <= nums[i] <= 10^9','-10^9 <= target <= 10^9','Only one valid answer exists.'],
  '{"Python":"class Solution:\n    def twoSum(self, nums, target):\n        seen = {}\n        for i, n in enumerate(nums):\n            if target - n in seen:\n                return [seen[target - n], i]\n            seen[n] = i\n        return []","JavaScript":"var twoSum = function(nums, target) {\n    const seen = {};\n    for (let i = 0; i < nums.length; i++) {\n        const complement = target - nums[i];\n        if (complement in seen) return [seen[complement], i];\n        seen[nums[i]] = i;\n    }\n    return [];\n};","Java":"class Solution {\n    public int[] twoSum(int[] nums, int target) {\n        Map<Integer, Integer> seen = new HashMap<>();\n        for (int i = 0; i < nums.length; i++) {\n            int complement = target - nums[i];\n            if (seen.containsKey(complement)) return new int[]{seen.get(complement), i};\n            seen.put(nums[i], i);\n        }\n        return new int[]{};\n    }\n}","C++":"class Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n        unordered_map<int, int> seen;\n        for (int i = 0; i < nums.size(); i++) {\n            if (seen.count(target - nums[i])) return {seen[target - nums[i]], i};\n            seen[nums[i]] = i;\n        }\n        return {};\n    }\n};","Go":"func twoSum(nums []int, target int) []int {\n    seen := make(map[int]int)\n    for i, n := range nums {\n        if j, ok := seen[target-n]; ok { return []int{j, i} }\n        seen[n] = i\n    }\n    return nil\n}"}'::jsonb,
  'https://leetcode.com/problems/two-sum/', 'https://neetcode.io/problems/two-integer-sum'
),
(
  'Valid Anagram', 'Easy', 'Arrays', ARRAY['Amazon','Google'],
  85.0, 50,
  'Given two strings `s` and `t`, return `true` if `t` is an anagram of `s`, and `false` otherwise.',
  '[{"input":"s = \"anagram\", t = \"nagaram\"","output":"true","explanation":"Both contain same characters."},{"input":"s = \"rat\", t = \"car\"","output":"false","explanation":"Different characters."}]'::jsonb,
  ARRAY['1 <= s.length, t.length <= 5 × 10^4','s and t consist of lowercase English letters.'],
  '{"Python":"class Solution:\n    def isAnagram(self, s, t):\n        return sorted(s) == sorted(t)","JavaScript":"var isAnagram = function(s, t) {\n    return s.split(\"\").sort().join(\"\") === t.split(\"\").sort().join(\"\");\n};","Java":"class Solution {\n    public boolean isAnagram(String s, String t) {\n        char[] a = s.toCharArray(); char[] b = t.toCharArray();\n        Arrays.sort(a); Arrays.sort(b);\n        return Arrays.equals(a, b);\n    }\n}","C++":"class Solution {\npublic:\n    bool isAnagram(string s, string t) {\n        sort(s.begin(),s.end()); sort(t.begin(),t.end()); return s==t;\n    }\n};","Go":"func isAnagram(s string, t string) bool {\n    a, b := []byte(s), []byte(t)\n    sort.Slice(a, func(i,j int) bool { return a[i] < a[j] })\n    sort.Slice(b, func(i,j int) bool { return b[i] < b[j] })\n    return string(a) == string(b)\n}"}'::jsonb,
  'https://leetcode.com/problems/valid-anagram/', 'https://neetcode.io/problems/is-anagram'
),
(
  'Contains Duplicate', 'Easy', 'Arrays', ARRAY['Amazon'],
  88.0, 50,
  'Given an integer array `nums`, return `true` if any value appears **at least twice** in the array, and return `false` if every element is distinct.',
  '[{"input":"nums = [1,2,3,1]","output":"true","explanation":"1 appears at index 0 and 3."},{"input":"nums = [1,2,3,4]","output":"false","explanation":"All elements are distinct."}]'::jsonb,
  ARRAY['1 <= nums.length <= 10^5','-10^9 <= nums[i] <= 10^9'],
  '{"Python":"class Solution:\n    def containsDuplicate(self, nums):\n        return len(nums) != len(set(nums))","JavaScript":"var containsDuplicate = function(nums) {\n    return nums.length !== new Set(nums).size;\n};","Java":"class Solution {\n    public boolean containsDuplicate(int[] nums) {\n        Set<Integer> seen = new HashSet<>();\n        for (int n : nums) if (!seen.add(n)) return true;\n        return false;\n    }\n}","C++":"class Solution {\npublic:\n    bool containsDuplicate(vector<int>& nums) {\n        return unordered_set<int>(nums.begin(), nums.end()).size() != nums.size();\n    }\n};","Go":"func containsDuplicate(nums []int) bool {\n    seen := make(map[int]bool)\n    for _, n := range nums { if seen[n] { return true }; seen[n] = true }\n    return false\n}"}'::jsonb,
  'https://leetcode.com/problems/contains-duplicate/', 'https://neetcode.io/problems/duplicate-integer'
),
(
  'Maximum Subarray', 'Medium', 'Dynamic Programming', ARRAY['Amazon','Apple','Microsoft'],
  77.0, 100,
  'Given an integer array `nums`, find the subarray with the largest sum, and return its sum. (Kadane''s Algorithm)',
  '[{"input":"nums = [-2,1,-3,4,-1,2,1,-5,4]","output":"6","explanation":"The subarray [4,-1,2,1] has the largest sum 6."},{"input":"nums = [1]","output":"1","explanation":"Single element."},{"input":"nums = [5,4,-1,7,8]","output":"23","explanation":"Entire array."}]'::jsonb,
  ARRAY['1 <= nums.length <= 10^5','-10^4 <= nums[i] <= 10^4'],
  '{"Python":"class Solution:\n    def maxSubArray(self, nums):\n        max_sum = cur = nums[0]\n        for n in nums[1:]:\n            cur = max(n, cur + n)\n            max_sum = max(max_sum, cur)\n        return max_sum","JavaScript":"var maxSubArray = function(nums) {\n    let max = nums[0], cur = nums[0];\n    for (let i = 1; i < nums.length; i++) {\n        cur = Math.max(nums[i], cur + nums[i]);\n        max = Math.max(max, cur);\n    }\n    return max;\n};","Java":"class Solution {\n    public int maxSubArray(int[] nums) {\n        int max = nums[0], cur = nums[0];\n        for (int i = 1; i < nums.length; i++) {\n            cur = Math.max(nums[i], cur + nums[i]);\n            max = Math.max(max, cur);\n        }\n        return max;\n    }\n}","C++":"class Solution {\npublic:\n    int maxSubArray(vector<int>& nums) {\n        int max = nums[0], cur = nums[0];\n        for (int i = 1; i < nums.size(); i++) {\n            cur = max_elem({nums[i], cur + nums[i]});\n            max = max_elem({max, cur});\n        }\n        return max;\n    }\n};","Go":"func maxSubArray(nums []int) int {\n    max, cur := nums[0], nums[0]\n    for _, n := range nums[1:] {\n        if cur+n > n { cur = cur + n } else { cur = n }\n        if cur > max { max = cur }\n    }\n    return max\n}"}'::jsonb,
  'https://leetcode.com/problems/maximum-subarray/', 'https://neetcode.io/problems/maximum-subarray'
),
(
  'Best Time to Buy and Sell Stock', 'Easy', 'Arrays', ARRAY['Amazon','Facebook'],
  83.0, 50,
  'You are given an array `prices` where `prices[i]` is the price of a given stock on the `i`th day. You want to maximize your profit by choosing a **single day** to buy one stock and choosing a **different day in the future** to sell that stock. Return the maximum profit you can achieve.',
  '[{"input":"prices = [7,1,5,3,6,4]","output":"5","explanation":"Buy on day 2 (price=1), sell on day 5 (price=6). Profit = 6-1 = 5."},{"input":"prices = [7,6,4,3,1]","output":"0","explanation":"Prices only decrease; no transaction = 0 profit."}]'::jsonb,
  ARRAY['1 <= prices.length <= 10^5','0 <= prices[i] <= 10^4'],
  '{"Python":"class Solution:\n    def maxProfit(self, prices):\n        min_p, max_p = float(\"inf\"), 0\n        for p in prices:\n            min_p = min(min_p, p)\n            max_p = max(max_p, p - min_p)\n        return max_p","JavaScript":"var maxProfit = function(prices) {\n    let min = Infinity, max = 0;\n    for (const p of prices) { min = Math.min(min, p); max = Math.max(max, p - min); }\n    return max;\n};","Java":"class Solution {\n    public int maxProfit(int[] prices) {\n        int min = Integer.MAX_VALUE, max = 0;\n        for (int p : prices) { min = Math.min(min, p); max = Math.max(max, p - min); }\n        return max;\n    }\n}","C++":"class Solution {\npublic:\n    int maxProfit(vector<int>& prices) {\n        int mn = INT_MAX, mx = 0;\n        for (int p : prices) { mn = min(mn, p); mx = max(mx, p - mn); }\n        return mx;\n    }\n};","Go":"func maxProfit(prices []int) int {\n    mn, mx := math.MaxInt, 0\n    for _, p := range prices { if p < mn { mn = p }; if p-mn > mx { mx = p - mn } }\n    return mx\n}"}'::jsonb,
  'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', 'https://neetcode.io/problems/buy-and-sell-crypto'
),
(
  'Climbing Stairs', 'Easy', 'Dynamic Programming', ARRAY['Amazon','Google','Adobe'],
  87.0, 50,
  'You are climbing a staircase. It takes `n` steps to reach the top. Each time you can either climb `1` or `2` steps. In how many distinct ways can you climb to the top?',
  '[{"input":"n = 2","output":"2","explanation":"1+1, or 2."},{"input":"n = 3","output":"3","explanation":"1+1+1, 1+2, or 2+1."}]'::jsonb,
  ARRAY['1 <= n <= 45'],
  '{"Python":"class Solution:\n    def climbStairs(self, n):\n        if n <= 2: return n\n        a, b = 1, 2\n        for _ in range(2, n):\n            a, b = b, a + b\n        return b","JavaScript":"var climbStairs = function(n) {\n    if (n <= 2) return n;\n    let a = 1, b = 2;\n    for (let i = 2; i < n; i++) [a, b] = [b, a + b];\n    return b;\n};","Java":"class Solution {\n    public int climbStairs(int n) {\n        if (n <= 2) return n;\n        int a = 1, b = 2;\n        for (int i = 2; i < n; i++) { int t = a + b; a = b; b = t; }\n        return b;\n    }\n}","C++":"class Solution {\npublic:\n    int climbStairs(int n) {\n        if (n <= 2) return n;\n        int a = 1, b = 2;\n        for (int i = 2; i < n; i++) { int t = a + b; a = b; b = t; }\n        return b;\n    }\n};","Go":"func climbStairs(n int) int {\n    if n <= 2 { return n }\n    a, b := 1, 2\n    for i := 2; i < n; i++ { a, b = b, a+b }\n    return b\n}"}'::jsonb,
  'https://leetcode.com/problems/climbing-stairs/', 'https://neetcode.io/problems/climbing-stairs'
),
(
  'Merge Two Sorted Lists', 'Easy', 'Linked Lists', ARRAY['Amazon','Google','Microsoft'],
  90.0, 50,
  'You are given the heads of two sorted linked lists `list1` and `list2`. Merge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists. Return the head of the merged linked list.',
  '[{"input":"list1 = [1,2,4], list2 = [1,3,4]","output":"[1,1,2,3,4,4]","explanation":"Merged sorted list."},{"input":"list1 = [], list2 = []","output":"[]","explanation":"Both empty."}]'::jsonb,
  ARRAY['The number of nodes in both lists is in the range [0, 50]','-100 <= Node.val <= 100','Both list1 and list2 are sorted in non-decreasing order.'],
  '{"Python":"class Solution:\n    def mergeTwoLists(self, l1, l2):\n        dummy = ListNode()\n        cur = dummy\n        while l1 and l2:\n            if l1.val <= l2.val: cur.next = l1; l1 = l1.next\n            else: cur.next = l2; l2 = l2.next\n            cur = cur.next\n        cur.next = l1 or l2\n        return dummy.next","JavaScript":"var mergeTwoLists = function(l1, l2) {\n    const dummy = new ListNode();\n    let cur = dummy;\n    while (l1 && l2) {\n        if (l1.val <= l2.val) { cur.next = l1; l1 = l1.next; }\n        else { cur.next = l2; l2 = l2.next; }\n        cur = cur.next;\n    }\n    cur.next = l1 ?? l2;\n    return dummy.next;\n};","Java":"class Solution {\n    public ListNode mergeTwoLists(ListNode l1, ListNode l2) {\n        ListNode dummy = new ListNode(), cur = dummy;\n        while (l1 != null && l2 != null) {\n            if (l1.val <= l2.val) { cur.next = l1; l1 = l1.next; }\n            else { cur.next = l2; l2 = l2.next; }\n            cur = cur.next;\n        }\n        cur.next = l1 != null ? l1 : l2;\n        return dummy.next;\n    }\n}","C++":"class Solution {\npublic:\n    ListNode* mergeTwoLists(ListNode* l1, ListNode* l2) {\n        ListNode dummy, *cur = &dummy;\n        while (l1 && l2) {\n            if (l1->val <= l2->val) { cur->next = l1; l1 = l1->next; }\n            else { cur->next = l2; l2 = l2->next; }\n            cur = cur->next;\n        }\n        cur->next = l1 ? l1 : l2;\n        return dummy.next;\n    }\n};","Go":"func mergeTwoLists(l1 *ListNode, l2 *ListNode) *ListNode {\n    dummy := &ListNode{}\n    cur := dummy\n    for l1 != nil && l2 != nil {\n        if l1.Val <= l2.Val { cur.Next = l1; l1 = l1.Next } else { cur.Next = l2; l2 = l2.Next }\n        cur = cur.Next\n    }\n    if l1 != nil { cur.Next = l1 } else { cur.Next = l2 }\n    return dummy.Next\n}"}'::jsonb,
  'https://leetcode.com/problems/merge-two-sorted-lists/', 'https://neetcode.io/problems/merge-two-sorted-linked-lists'
),
(
  'Valid Parentheses', 'Easy', 'Stacks', ARRAY['Amazon','Google','Facebook'],
  80.0, 50,
  'Given a string `s` containing just the characters `(`, `)`, `{`, `}`, `[` and `]`, determine if the input string is valid. An input string is valid if: Open brackets must be closed by the same type of brackets, and in the correct order.',
  '[{"input":"s = \"()\"","output":"true","explanation":"Simple valid pair."},{"input":"s = \"()[]{}\"","output":"true","explanation":"Three valid pairs."},{"input":"s = \"(]\"","output":"false","explanation":"Mismatched brackets."}]'::jsonb,
  ARRAY['1 <= s.length <= 10^4','s consists of parentheses only ''()[]{}''.'],
  '{"Python":"class Solution:\n    def isValid(self, s):\n        stack, match = [], {')': '(', ']': '[', '}': '{'}\n        for c in s:\n            if c in match:\n                if not stack or stack[-1] != match[c]: return False\n                stack.pop()\n            else: stack.append(c)\n        return not stack","JavaScript":"var isValid = function(s) {\n    const stack = [], match = {')':\''(', ']': '[', '}': '{'};\n    for (const c of s) {\n        if (c in match) { if (stack.pop() !== match[c]) return false; }\n        else stack.push(c);\n    }\n    return !stack.length;\n};","Java":"class Solution {\n    public boolean isValid(String s) {\n        Deque<Character> stack = new ArrayDeque<>();\n        for (char c : s.toCharArray()) {\n            if (c==')') { if (stack.isEmpty()||stack.pop()!='(') return false; }\n            else if (c==']') { if (stack.isEmpty()||stack.pop()!='[') return false; }\n            else if (c=='}') { if (stack.isEmpty()||stack.pop()!='{') return false; }\n            else stack.push(c);\n        }\n        return stack.isEmpty();\n    }\n}","C++":"class Solution {\npublic:\n    bool isValid(string s) {\n        stack<char> st;\n        for (char c : s) {\n            if (c==')') { if (st.empty()||st.top()!='(') return false; st.pop(); }\n            else if (c==']') { if (st.empty()||st.top()!='[') return false; st.pop(); }\n            else if (c=='}') { if (st.empty()||st.top()!='{') return false; st.pop(); }\n            else st.push(c);\n        }\n        return st.empty();\n    }\n};","Go":"func isValid(s string) bool {\n    stack := []rune{}\n    match := map[rune]rune{')':'(', ']':'[', '}':'{'}\n    for _, c := range s {\n        if m, ok := match[c]; ok {\n            if len(stack)==0 || stack[len(stack)-1]!=m { return false }\n            stack = stack[:len(stack)-1]\n        } else { stack = append(stack, c) }\n    }\n    return len(stack)==0\n}"}'::jsonb,
  'https://leetcode.com/problems/valid-parentheses/', 'https://neetcode.io/problems/validate-parentheses'
),
(
  'Coin Change', 'Medium', 'Dynamic Programming', ARRAY['Amazon','Google','Facebook'],
  67.0, 100,
  'You are given an integer array `coins` representing coins of different denominations and an integer `amount` representing a total amount of money. Return the fewest number of coins that you need to make up that amount. If that amount cannot be made up by any combination of the coins, return `-1`.',
  '[{"input":"coins = [1,5,11], amount = 11","output":"1","explanation":"11 itself gives 1 coin."},{"input":"coins = [1,2,5], amount = 11","output":"3","explanation":"5+5+1 = 11."},{"input":"coins = [2], amount = 3","output":"-1","explanation":"Cannot make 3 with only coin denomination 2."}]'::jsonb,
  ARRAY['1 <= coins.length <= 12','1 <= coins[i] <= 2^31 - 1','0 <= amount <= 10^4'],
  '{"Python":"class Solution:\n    def coinChange(self, coins, amount):\n        dp = [float(\"inf\")] * (amount + 1)\n        dp[0] = 0\n        for a in range(1, amount + 1):\n            for c in coins:\n                if a - c >= 0: dp[a] = min(dp[a], dp[a - c] + 1)\n        return dp[amount] if dp[amount] != float(\"inf\") else -1","JavaScript":"var coinChange = function(coins, amount) {\n    const dp = new Array(amount+1).fill(Infinity); dp[0] = 0;\n    for (let a = 1; a <= amount; a++)\n        for (const c of coins)\n            if (a - c >= 0) dp[a] = Math.min(dp[a], dp[a-c]+1);\n    return dp[amount] === Infinity ? -1 : dp[amount];\n};","Java":"class Solution {\n    public int coinChange(int[] coins, int amount) {\n        int[] dp = new int[amount+1];\n        Arrays.fill(dp, amount+1);\n        dp[0] = 0;\n        for (int a = 1; a <= amount; a++)\n            for (int c : coins)\n                if (a - c >= 0) dp[a] = Math.min(dp[a], dp[a-c]+1);\n        return dp[amount] > amount ? -1 : dp[amount];\n    }\n}","C++":"class Solution {\npublic:\n    int coinChange(vector<int>& coins, int amount) {\n        vector<int> dp(amount+1, amount+1); dp[0] = 0;\n        for (int a = 1; a <= amount; a++)\n            for (int c : coins)\n                if (a-c >= 0) dp[a] = min(dp[a], dp[a-c]+1);\n        return dp[amount] > amount ? -1 : dp[amount];\n    }\n};","Go":"func coinChange(coins []int, amount int) int {\n    dp := make([]int, amount+1)\n    for i := range dp { dp[i] = amount+1 }\n    dp[0] = 0\n    for a := 1; a <= amount; a++ {\n        for _, c := range coins {\n            if a-c >= 0 && dp[a-c]+1 < dp[a] { dp[a] = dp[a-c]+1 }\n        }\n    }\n    if dp[amount] > amount { return -1 }\n    return dp[amount]\n}"}'::jsonb,
  'https://leetcode.com/problems/coin-change/', 'https://neetcode.io/problems/coin-change'
),
(
  'Number of Islands', 'Medium', 'Graphs', ARRAY['Amazon','Google','Bloomberg'],
  72.0, 100,
  'Given an `m x n` 2D binary grid `grid` which represents a map of `1`s (land) and `0`s (water), return the number of islands. An **island** is surrounded by water and is formed by connecting adjacent lands horizontally or vertically.',
  '[{"input":"grid = [[\"1\",\"1\",\"1\",\"1\",\"0\"],[\"1\",\"1\",\"0\",\"1\",\"0\"],[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"0\",\"0\",\"0\",\"0\",\"0\"]]","output":"1","explanation":"One large island."},{"input":"grid = [[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"0\",\"0\",\"1\",\"0\",\"0\"],[\"0\",\"0\",\"0\",\"1\",\"1\"]]","output":"3","explanation":"Three separate islands."}]'::jsonb,
  ARRAY['m == grid.length','n == grid[i].length','1 <= m, n <= 300','grid[i][j] is ''0'' or ''1''.'],
  '{"Python":"class Solution:\n    def numIslands(self, grid):\n        count = 0\n        def dfs(r, c):\n            if r < 0 or r >= len(grid) or c < 0 or c >= len(grid[0]) or grid[r][c] != \"1\": return\n            grid[r][c] = \"0\"\n            for dr, dc in [(0,1),(0,-1),(1,0),(-1,0)]: dfs(r+dr, c+dc)\n        for r in range(len(grid)):\n            for c in range(len(grid[0])):\n                if grid[r][c] == \"1\": count += 1; dfs(r, c)\n        return count","JavaScript":"var numIslands = function(grid) {\n    let count = 0;\n    const dfs = (r,c) => {\n        if (r<0||r>=grid.length||c<0||c>=grid[0].length||grid[r][c]!==\"1\") return;\n        grid[r][c] = \"0\";\n        [[0,1],[0,-1],[1,0],[-1,0]].forEach(([dr,dc])=>dfs(r+dr,c+dc));\n    };\n    for (let r=0;r<grid.length;r++) for (let c=0;c<grid[0].length;c++) if (grid[r][c]===\"1\") { count++; dfs(r,c); }\n    return count;\n};","Java":"class Solution {\n    public int numIslands(char[][] g) {\n        int count = 0;\n        for (int r=0;r<g.length;r++) for (int c=0;c<g[0].length;c++) if (g[r][c]==\"1\") { count++; dfs(g,r,c); }\n        return count;\n    }\n    void dfs(char[][] g, int r, int c) {\n        if (r<0||r>=g.length||c<0||c>=g[0].length||g[r][c]!=\"1\") return;\n        g[r][c] = \"0\";\n        dfs(g,r+1,c); dfs(g,r-1,c); dfs(g,r,c+1); dfs(g,r,c-1);\n    }\n}","C++":"class Solution {\npublic:\n    int numIslands(vector<vector<char>>& g) {\n        int count = 0;\n        for (int r=0;r<g.size();r++) for (int c=0;c<g[0].size();c++) if (g[r][c]==\"1\") { count++; dfs(g,r,c); }\n        return count;\n    }\n    void dfs(vector<vector<char>>& g, int r, int c) {\n        if (r<0||r>=(int)g.size()||c<0||c>=(int)g[0].size()||g[r][c]!=\"1\") return;\n        g[r][c] = \"0\";\n        dfs(g,r+1,c); dfs(g,r-1,c); dfs(g,r,c+1); dfs(g,r,c-1);\n    }\n};","Go":"func numIslands(grid [][]byte) int {\n    count := 0\n    var dfs func(r, c int)\n    dfs = func(r, c int) {\n        if r<0||r>=len(grid)||c<0||c>=len(grid[0])||grid[r][c]!=\"1\" { return }\n        grid[r][c] = \"0\"\n        dfs(r+1,c); dfs(r-1,c); dfs(r,c+1); dfs(r,c-1)\n    }\n    for r := range grid { for c := range grid[0] { if grid[r][c]==\"1\" { count++; dfs(r,c) } } }\n    return count\n}"}'::jsonb,
  'https://leetcode.com/problems/number-of-islands/', 'https://neetcode.io/problems/count-number-of-islands'
);

-- Seed some default flashcard decks + cards for new users (global, not per-user)
-- These won't be created here — they're created when users sign up.
-- To pre-populate flashcards, use the admin panel or a separate seeding script.
