import { PageHeader } from "@/components/app-layout";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { createFileRoute } from "@tanstack/react-router";
import { Youtube, Sparkles, Copy, Save, Download, Play, Clock, BookOpen, Tag, History, Star, Printer, ChevronRight } from "lucide-react";
import { useState } from "react";
import { useAuth } from "@/hooks/use-auth";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { summarizeVideo, getSummaries, saveSummaryToNotes } from "@/server-actions/youtube";
import { toast } from "sonner";

export const Route = createFileRoute("/_app/youtube-summarizer")({ component: YT });

function YT() {
  const { session } = useAuth();
  const queryClient = useQueryClient();
  
  const [url, setUrl] = useState("");
  const [length, setLength] = useState<"Short" | "Medium" | "Detailed">("Medium");
  const [activeSummary, setActiveSummary] = useState<any>(null);

  const { data: history = [] } = useQuery({
    queryKey: ["yt_summaries"],
    queryFn: () => getSummaries({ data: { token: session?.access_token || "" } }),
    enabled: !!session?.access_token,
  });

  const summarizeMutation = useMutation({
    mutationFn: (ytUrl: string) => summarizeVideo({ data: { token: session!.access_token, url: ytUrl, length } }),
    onSuccess: (data) => {
      setActiveSummary(data);
      queryClient.invalidateQueries({ queryKey: ["yt_summaries"] });
      toast.success("Summary generated successfully!");
    },
    onError: (err: any) => {
      toast.error(err.message || "Failed to generate summary");
    }
  });

  const saveToNotesMutation = useMutation({
    mutationFn: () => saveSummaryToNotes({ data: { token: session!.access_token, summaryId: activeSummary.id } }),
    onSuccess: () => {
      toast.success("Saved to your notes!");
    },
    onError: (err: any) => {
      toast.error(err.message || "Failed to save to notes");
    }
  });

  const generate = () => {
    if (!url) return toast.error("Please enter a YouTube URL");
    summarizeMutation.mutate(url);
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast.success("Copied to clipboard!");
  };

  const downloadMarkdown = () => {
    if (!activeSummary) return;
    const md = `# ${activeSummary.title}\n\n**Channel:** ${activeSummary.channel}\n**Length:** ${length}\n\n## Summary\n${activeSummary.detailed_summary || activeSummary.summary}\n\n## Key Points\n${activeSummary.key_points?.map((p: string) => `- ${p}`).join("\n")}\n\n## Concepts\n${activeSummary.concepts?.map((c: string) => `- ${c}`).join("\n")}\n\n## Revision Notes\n${activeSummary.revision_notes}\n\n*Generated by Adaptivly Mastered AI*`;
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${activeSummary.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_summary.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const printPdf = () => {
    window.print(); // Simple browser-native PDF export
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="YouTube Summarizer"
        description="Turn any lecture into interview-ready notes in seconds."
      />

      {/* URL input */}
      <Card className="relative overflow-hidden border-0 p-0 shadow-elegant">
        <div className="absolute inset-0 bg-gradient-primary" />
        <div className="absolute inset-0 bg-gradient-mesh opacity-30" />
        <div className="relative p-8">
          <div className="flex items-center gap-2 mb-4">
            <Youtube className="h-5 w-5 text-primary-foreground" />
            <span className="font-bold text-primary-foreground">Paste a YouTube URL</span>
          </div>
          <div className="flex flex-col gap-3 sm:flex-row">
            <div className="relative flex-1">
              <Youtube className="pointer-events-none absolute left-3.5 top-1/2 h-4.5 w-4.5 -translate-y-1/2 text-red-500" />
              <Input
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                className="h-12 pl-11 rounded-xl border-white/20 bg-white/10 text-white placeholder:text-white/50 focus:bg-white/20"
                placeholder="https://youtube.com/watch?v=..."
              />
            </div>
            
            <Select value={length} onValueChange={(val: any) => setLength(val)}>
              <SelectTrigger className="h-12 w-[140px] bg-white/10 text-white border-white/20 rounded-xl">
                <SelectValue placeholder="Length" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="Short">Short</SelectItem>
                <SelectItem value="Medium">Medium</SelectItem>
                <SelectItem value="Detailed">Detailed</SelectItem>
              </SelectContent>
            </Select>

            <Button
              onClick={generate}
              disabled={summarizeMutation.isPending}
              className="h-12 bg-white text-primary font-bold px-8 rounded-xl hover:bg-white/90 shadow-elegant gap-2 shrink-0"
            >
              {summarizeMutation.isPending ? (
                <>
                  <div className="h-4 w-4 animate-spin rounded-full border-2 border-primary border-t-transparent" />
                  Processing...
                </>
              ) : (
                <>
                  <Sparkles className="h-4 w-4" /> Generate
                </>
              )}
            </Button>
          </div>
        </div>
      </Card>

      {activeSummary && (
        <div className="space-y-6 print:space-y-4 print:text-black">
          {/* Video info */}
          <Card className="border-border/40 p-5 shadow-soft">
            <div className="flex items-start gap-4">
              <div className="relative shrink-0 print:hidden">
                <div className="h-20 w-32 rounded-xl bg-gradient-primary flex items-center justify-center shadow-glow">
                  <Play className="h-8 w-8 text-primary-foreground" />
                </div>
                <div className="absolute -bottom-1.5 -right-1.5 rounded-lg bg-card border border-border px-1.5 py-0.5 text-[10px] font-bold">
                  {activeSummary.duration || "N/A"}
                </div>
              </div>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-base leading-tight">{activeSummary.title}</h3>
                <p className="text-xs text-muted-foreground mt-1">{activeSummary.channel}</p>
                <div className="mt-3 flex flex-wrap gap-2">
                  {activeSummary.tags?.map((t: string) => (
                    <Badge key={t} variant="outline" className="text-xs">{t}</Badge>
                  ))}
                </div>
              </div>
              <div className="flex items-center gap-1 shrink-0 print:hidden">
                <Button variant="ghost" size="icon" className="h-8 w-8 rounded-lg" onClick={() => setActiveSummary(null)}>
                  <History className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </Card>

          {/* Action Buttons - Print Hidden */}
          <div className="flex justify-end gap-2 print:hidden">
            <Button variant="outline" onClick={() => copyToClipboard(activeSummary.detailed_summary || activeSummary.summary)}>
              <Copy className="h-4 w-4 mr-2" /> Copy Notes
            </Button>
            <Button variant="outline" onClick={printPdf}>
              <Printer className="h-4 w-4 mr-2" /> Save PDF
            </Button>
            <Button variant="outline" onClick={downloadMarkdown}>
              <Download className="h-4 w-4 mr-2" /> Markdown
            </Button>
            <Button onClick={() => saveToNotesMutation.mutate()} disabled={saveToNotesMutation.isPending} className="bg-gradient-primary">
              <Save className="h-4 w-4 mr-2" /> {saveToNotesMutation.isPending ? "Saving..." : "Save to Notebook"}
            </Button>
          </div>

          {/* Summary tabs */}
          <Tabs defaultValue="summary" className="print:block">
            <TabsList className="rounded-xl print:hidden">
              <TabsTrigger value="summary" className="rounded-lg">Summary</TabsTrigger>
              <TabsTrigger value="details" className="rounded-lg">Concepts & Notes</TabsTrigger>
              <TabsTrigger value="raw" className="rounded-lg">Transcript</TabsTrigger>
            </TabsList>

            <TabsContent value="summary" className="mt-4 print:block">
              <Card className="border-border/40 p-6 shadow-soft">
                <h3 className="font-bold mb-4 text-xl">Overview</h3>
                <div className="prose prose-sm max-w-none text-muted-foreground leading-relaxed space-y-4">
                  {(activeSummary.summary || "").split('\n').map((para: string, i: number) => (
                    para.trim() && <p key={i}>{para}</p>
                  ))}
                </div>
              </Card>
            </TabsContent>

            <TabsContent value="details" className="mt-4 print:block">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <Card className="border-border/40 p-6 shadow-soft">
                  <h3 className="font-bold mb-4 text-primary">Key Concepts</h3>
                  <div className="space-y-4">
                    <div>
                      <div className="flex flex-wrap gap-2">
                        {activeSummary.concepts?.map((c: string) => (
                          <Badge key={c} className="bg-primary/10 text-primary border-primary/30 hover:bg-primary/20">{c}</Badge>
                        ))}
                      </div>
                    </div>
                  </div>
                </Card>

                <Card className="border-border/40 p-6 shadow-soft">
                  <h3 className="font-bold mb-4 text-amber-600">Interview Notes</h3>
                  <ul className="space-y-3 mb-6">
                    {activeSummary.key_points?.map((p: string, i: number) => (
                      <li key={i} className="flex items-start gap-3 text-sm">
                        <div className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-gradient-primary" />
                        <span className="text-muted-foreground">{p}</span>
                      </li>
                    ))}
                  </ul>
                </Card>
              </div>
            </TabsContent>

            <TabsContent value="raw" className="mt-4 print:hidden">
              <Card className="border-border/40 p-6 shadow-soft">
                <h3 className="font-bold mb-4">Raw Transcript</h3>
                <div className="rounded-xl border border-border/40 bg-muted/20 p-4 font-mono text-xs leading-loose text-muted-foreground max-h-80 overflow-y-auto whitespace-pre-wrap">
                  {activeSummary.raw_transcript}
                </div>
              </Card>
            </TabsContent>
          </Tabs>
        </div>
      )}

      {/* History */}
      {!activeSummary && (
        <Card className="border-border/40 p-6 shadow-soft">
          <div className="flex items-center gap-2 mb-4">
            <History className="h-4 w-4 text-primary" />
            <h3 className="font-bold">Recent summaries</h3>
          </div>
          <div className="space-y-2">
            {history.length === 0 && <p className="text-sm text-muted-foreground">No summaries yet.</p>}
            {history.map((h: any) => (
              <div
                key={h.id}
                onClick={() => setActiveSummary(h)}
                className="flex items-center gap-4 rounded-xl border border-border/40 p-4 hover:border-primary/30 hover:bg-primary/5 transition-all cursor-pointer group"
              >
                <div className="grid h-10 w-10 place-items-center rounded-xl bg-red-500/10 text-red-500 shrink-0">
                  <Youtube className="h-5 w-5" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="text-sm font-semibold truncate">{h.title}</div>
                  <div className="flex items-center gap-3 mt-1 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1"><Clock className="h-3 w-3" />{h.duration || "N/A"}</span>
                    {h.tags?.slice(0, 3).map((t: string) => (
                      <Badge key={t} variant="outline" className="h-4 text-[10px]">{t}</Badge>
                    ))}
                  </div>
                </div>
                <div className="text-xs text-muted-foreground shrink-0">{new Date(h.created_at).toLocaleDateString()}</div>
              </div>
            ))}
          </div>
        </Card>
      )}
    </div>
  );
}
