/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AppAchievementsRouteImport } from './routes/_app.achievements'
import { Route as AppAiTutorRouteImport } from './routes/_app.ai-tutor'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAssessmentRouteImport } from './routes/_app.assessment'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppFlashcardsRouteImport } from './routes/_app.flashcards'
import { Route as AppLearningPathsRouteImport } from './routes/_app.learning-paths'
import { Route as AppMockInterviewsRouteImport } from './routes/_app.mock-interviews'
import { Route as AppNotesRouteImport } from './routes/_app.notes'
import { Route as AppPlannerRouteImport } from './routes/_app.planner'
import { Route as AppPracticeRouteImport } from './routes/_app.practice'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSubjectsRouteImport } from './routes/_app.subjects'
import { Route as AppYoutubeSummarizerRouteImport } from './routes/_app.youtube-summarizer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppAiTutorRoute = AppAiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentRoute = AppAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsRoute = AppFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningPathsRoute = AppLearningPathsRouteImport.update({
  id: '/learning-paths',
  path: '/learning-paths',
  getParentRoute: () => AppRoute,
} as any)
const AppMockInterviewsRoute = AppMockInterviewsRouteImport.update({
  id: '/mock-interviews',
  path: '/mock-interviews',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeRoute = AppPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppYoutubeSummarizerRoute = AppYoutubeSummarizerRouteImport.update({
  id: '/youtube-summarizer',
  path: '/youtube-summarizer',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/achievements': typeof AppAchievementsRoute
  '/ai-tutor': typeof AppAiTutorRoute
  '/analytics': typeof AppAnalyticsRoute
  '/assessment': typeof AppAssessmentRoute
  '/dashboard': typeof AppDashboardRoute
  '/flashcards': typeof AppFlashcardsRoute
  '/learning-paths': typeof AppLearningPathsRoute
  '/mock-interviews': typeof AppMockInterviewsRoute
  '/notes': typeof AppNotesRoute
  '/planner': typeof AppPlannerRoute
  '/practice': typeof AppPracticeRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/subjects': typeof AppSubjectsRoute
  '/youtube-summarizer': typeof AppYoutubeSummarizerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/achievements': typeof AppAchievementsRoute
  '/ai-tutor': typeof AppAiTutorRoute
  '/analytics': typeof AppAnalyticsRoute
  '/assessment': typeof AppAssessmentRoute
  '/dashboard': typeof AppDashboardRoute
  '/flashcards': typeof AppFlashcardsRoute
  '/learning-paths': typeof AppLearningPathsRoute
  '/mock-interviews': typeof AppMockInterviewsRoute
  '/notes': typeof AppNotesRoute
  '/planner': typeof AppPlannerRoute
  '/practice': typeof AppPracticeRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/subjects': typeof AppSubjectsRoute
  '/youtube-summarizer': typeof AppYoutubeSummarizerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/achievements': typeof AppAchievementsRoute
  '/_app/ai-tutor': typeof AppAiTutorRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/assessment': typeof AppAssessmentRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/flashcards': typeof AppFlashcardsRoute
  '/_app/learning-paths': typeof AppLearningPathsRoute
  '/_app/mock-interviews': typeof AppMockInterviewsRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/planner': typeof AppPlannerRoute
  '/_app/practice': typeof AppPracticeRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/subjects': typeof AppSubjectsRoute
  '/_app/youtube-summarizer': typeof AppYoutubeSummarizerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/verify-email'
    | '/achievements'
    | '/ai-tutor'
    | '/analytics'
    | '/assessment'
    | '/dashboard'
    | '/flashcards'
    | '/learning-paths'
    | '/mock-interviews'
    | '/notes'
    | '/planner'
    | '/practice'
    | '/profile'
    | '/settings'
    | '/subjects'
    | '/youtube-summarizer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/verify-email'
    | '/achievements'
    | '/ai-tutor'
    | '/analytics'
    | '/assessment'
    | '/dashboard'
    | '/flashcards'
    | '/learning-paths'
    | '/mock-interviews'
    | '/notes'
    | '/planner'
    | '/practice'
    | '/profile'
    | '/settings'
    | '/subjects'
    | '/youtube-summarizer'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/verify-email'
    | '/_app/achievements'
    | '/_app/ai-tutor'
    | '/_app/analytics'
    | '/_app/assessment'
    | '/_app/dashboard'
    | '/_app/flashcards'
    | '/_app/learning-paths'
    | '/_app/mock-interviews'
    | '/_app/notes'
    | '/_app/planner'
    | '/_app/practice'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/subjects'
    | '/_app/youtube-summarizer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/achievements': {
      id: '/_app/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-tutor': {
      id: '/_app/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/ai-tutor'
      preLoaderRoute: typeof AppAiTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessment': {
      id: '/_app/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AppAssessmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flashcards': {
      id: '/_app/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AppFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learning-paths': {
      id: '/_app/learning-paths'
      path: '/learning-paths'
      fullPath: '/learning-paths'
      preLoaderRoute: typeof AppLearningPathsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mock-interviews': {
      id: '/_app/mock-interviews'
      path: '/mock-interviews'
      fullPath: '/mock-interviews'
      preLoaderRoute: typeof AppMockInterviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planner': {
      id: '/_app/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice': {
      id: '/_app/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AppPracticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects': {
      id: '/_app/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/youtube-summarizer': {
      id: '/_app/youtube-summarizer'
      path: '/youtube-summarizer'
      fullPath: '/youtube-summarizer'
      preLoaderRoute: typeof AppYoutubeSummarizerRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppAiTutorRoute: typeof AppAiTutorRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssessmentRoute: typeof AppAssessmentRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFlashcardsRoute: typeof AppFlashcardsRoute
  AppLearningPathsRoute: typeof AppLearningPathsRoute
  AppMockInterviewsRoute: typeof AppMockInterviewsRoute
  AppNotesRoute: typeof AppNotesRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppPracticeRoute: typeof AppPracticeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubjectsRoute: typeof AppSubjectsRoute
  AppYoutubeSummarizerRoute: typeof AppYoutubeSummarizerRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppAiTutorRoute: AppAiTutorRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssessmentRoute: AppAssessmentRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFlashcardsRoute: AppFlashcardsRoute,
  AppLearningPathsRoute: AppLearningPathsRoute,
  AppMockInterviewsRoute: AppMockInterviewsRoute,
  AppNotesRoute: AppNotesRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppPracticeRoute: AppPracticeRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubjectsRoute: AppSubjectsRoute,
  AppYoutubeSummarizerRoute: AppYoutubeSummarizerRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
